# GitHub CI configuration file for LuaVela.
# Copyright (C) 2020-2024 LuaVela Authors. See Copyright Notice in COPYRIGHT
# Copyright (C) 2015-2020 IPONWEB Ltd. See Copyright Notice in COPYRIGHT

name: Setup CI environment
description: Common part to tweak CI runner environment
runs:
  using: composite
  steps:
    - run: |
        # Set BUILDDIR environment variable to specify uJIT build directory.
        echo BUILDDIR=${{ runner.temp }}/build-${{ github.run_id }} | tee -a $GITHUB_ENV
      shell: bash
