# This is a part of uJIT's testing suite.
# Copyright (C) 2020-2021 LuaVela Authors. See Copyright Notice in COPYRIGHT
# Copyright (C) 2015-2020 IPONWEB Ltd. See Copyright Notice in COPYRIGHT

list(APPEND SUITE_SOURCES
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/CMakeLists.txt
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bc_hotcnt
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bc_hotcnt/all.lua
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/test_ext_events
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/test_ext_events/tracing_during_timeout.lua
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/test_gc_traverse_stack
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/test_gc_traverse_stack/gc_after_mm_exit.lua
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/test_gc_traverse_stack/gc_before_mm_exit.lua
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/test_profiler_and_timeouts
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/test_profiler_and_timeouts/profile_timeouts.lua
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/test_stack_resize
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/test_stack_resize/rec_ff.lua
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_api_args.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_bottom_dummy.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_cci_immutable.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_common.h
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_common_lua.h
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_concat_and_gc.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_crc.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_cstr.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_emit_sse2.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_errmem.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_example.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_ext_events.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_gc_traversal_mm.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_gc_traverse_stack.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_leb128.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_alloc.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_concat.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_coverage.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_equal.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_getfield.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_gettable.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_hotcnt.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_iprof.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_lessthan.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_setfield.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_settable.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_timeout.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_lua_yield.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_luae_createstate.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_luae_deepcopy.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_luae_immutable.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_luae_iterate.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_luae_requiref.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_luae_seal.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_luae_table.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_math_fold.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_profiler.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_profiler_and_timeouts.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_random.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_sbuf.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_stack_resize.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_store_num_key.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_str.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_strscan.c
 ${CMAKE_CURRENT_SOURCE_DIR}/suite/test_vmstate.c
)
