
# This is a part of uJIT's testing suite.
# Copyright (C) 2020-2024 LuaVela Authors. See Copyright Notice in COPYRIGHT
# Copyright (C) 2015-2020 IPONWEB Ltd. See Copyright Notice in COPYRIGHT

list(APPEND SUITE_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/api-extended.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/bit.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/api-extended
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/api-extended/api-extended.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/api-extended/api-nargs.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bc_hotcnt
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bc_hotcnt/forl.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bc_hotcnt/funcf.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bc_hotcnt/iterl.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bc_hotcnt/loop_goto.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bc_hotcnt/loop_repeat.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bc_hotcnt/loop_while.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bit
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/bit/tohex.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/cli-X
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/cli-X/any.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-abs-neg
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-abs-neg/abs-neg.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-concat
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-concat/concat.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-concat/no-tbar-cse.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-getfenv
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-getfenv/getfenv.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-sink
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-sink/nosink.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-sink/partsinkouter.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-sink/partsinkstore.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/compiler-sink/sink.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/coverage
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/coverage/coverage_gc.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/coverage/coverage_if_then.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/coverage/coverage_middle_jump.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/coverage/coverage_pause.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/coverage/coverage_simple.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/coverage/coverage_varinfo.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/coverage/exclude.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/coverage/wrapper.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-compiler
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-compiler/arith.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-compiler/assertions.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-compiler/bindings.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-compiler/bitwise.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-compiler/calls.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-compiler/memrefs.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-compiler/progress.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-compiler/strings.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-compiler/upvalues.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-stack
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dump-stack/frames.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/bad-arg-1.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/bad-arg-2.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/bad-arg-num.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/chunk.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/dumpbcins.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/fast-function.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/long-chunk-name-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/long-source-lines.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/reference-dump.bc
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/source-dump-test-chunk.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/dumpbc/try-overflow-hint-buffer.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/errors
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/errors/errors.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable-global.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable-jit-metatable.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable-jit-tsetb.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable-jit-tsets.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable-jit-tsetv.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable-mark-fwd.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable-recording-mixed-types-1.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable-recording-mixed-types-2.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable-recording-simple.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable-recording.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/immutable/immutable.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/load
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/load/loop_lookup.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/load/mt.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/load/niltvg.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/load/no_index.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/load/nonnil.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/load/num_mt_nil_index.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/load/num_mt_table_index.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store/loop_lookup.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store/mt.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store/nil_mm.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store/nil_newindex.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store/nil_nomm_newref_conv.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store/nil_nomm_nonewref.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store/no_newindex.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store/nonnil_mt.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store/nonnil_nomt.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/ir_indexed/store/table_newindex.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/jit-options
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/jit-options/jitcat.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/jit-options/nohrefk.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/jit-options/noretl.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/leb128
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/leb128/bc-dump-reference.out
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/leb128/bc-dump.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/leb128/syntax-error.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/coercion.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/fp-classify.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/frexp.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/jitatrig.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/jit-fp-classify.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/jitexp.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/jitexp2.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/jithtrig.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/jitpow.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/jitpowi.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/jitpows.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/jitpowsimple.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/jitpowsqrt.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/modf.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/nan.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/math/test_function.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/memprof
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/memprof/duration.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/memprof/memprof.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/meta-comp
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/meta-comp/meta-comp-lt.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/metrics-gc
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/metrics-gc/allocated-freed.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/metrics-gc/gcsteps.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/metrics-snap-restores
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/metrics-snap-restores/loop-direct.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/metrics-snap-restores/loop-side-exit-non-compiled.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/metrics-snap-restores/loop-side-exit.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/metrics-snap-restores/scalar.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/metrics-strhash
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/metrics-strhash/strhash.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/apart.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/apart-scalar.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/fload-meta-guard.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/gset.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/hpart-newref.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/hpart-newref-meta-guard.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/hpart-no-newref.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/hpart-no-newref-hoisting.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/hpart-no-newref-partial.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/in-place.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/load-used-by-assert.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/load-used-by-bc-isf.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/load-used-by-bc-ist.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/load-used-by-bc-not.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/no-fuse-meta-src.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/no-fuse-meta-dst.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/pri-nil-empty.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/pri-nil-non-empty.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/pri-non-nil.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/same-table-diff-keys.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/same-table-same-key.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/sload-meta-guard.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/movtv/tvload-meta-guard.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/neg-zero-for-step
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/neg-zero-for-step/forever.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/neg-zero-for-step/no-iter.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/array_hash_bound.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/array_hash_bound_1.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/array_hash_bound_2.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/array_last_no_hash.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/array_middle.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/from_mad.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/hash_last.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/hash_middle.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/nil_key.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/nil_key_no_array.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/self_modify.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/self_modify_1.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/pairs/self_modify_2.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf/callgraph.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf/coro-vm-state.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf/coro-yield-resume.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf/ff-vm-state.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf/mm-continuation.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf/profile_aux.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf/restart.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf/simple.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf/tail-call-ff.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile-leaf/tail-call.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/profile/profile.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/seal
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/seal/seal-proto.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/seal/seal-with-metatable-jit.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/seal/seal-without-metatable-jit-tsetb.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/seal/seal-without-metatable-jit-tsets.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/seal/seal-without-metatable-jit-tsetv.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/seal/seal.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/bufhdr-append.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/bufput-fuse.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/bufput-const-fold.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/bufstr-const-fold.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/bufstr-cse.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/find-init-arg.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/find-plain-load.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/find-plain.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/find-side-exit.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/find-upper-lower-recording.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/find.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/format.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/jit-trim.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/split.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/string/trim.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/concat
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/concat/concat.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/concat/concat_error.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/concat/concat_throw_on_recording1.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/concat/concat_throw_on_recording2.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/data.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/debug.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/mm
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/mm/nargs.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/naive.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/recording
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/recording.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/recording/asize_shallowcopy.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/recording/hload_shallowcopy.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/recording/href_store_shallowcopy.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/recording/sink_shallowcopy.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/recording/tbar_shallowcopy.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/rindex/interface.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/rindex/no-recording.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/rindex/recording.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/size
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/size/error_handling.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/size/size.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/size/size_recording.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/size/throw_on_recording.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/table_creation_tests.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/tests.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/throw_on_recording.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/toset
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/toset/literals.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/toset/mutated.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/table/utils.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/usesfenv
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/chunks/usesfenv/usesfenv.lua
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/cli-X.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/compiler-abs-neg.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/compiler-concat.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/compiler-getfenv.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/coverage.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/dump-compiler.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/dump-stack.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/dumpbc.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/errors.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/hotcnt.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/immutable.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/ir_indexed.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/jit-options.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/leb128.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/lib
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/lib/UJit
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/lib/UJit/Test.pm
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/math.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/memprof.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/meta-comp.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/metrics-gc.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/metrics-snap-restores.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/metrics-strhash.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/movtv.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/neg-zero-for-step.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/os.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/pairs.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/profile-leaf.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/profile.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/seal.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/sink.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/string.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/table.t
  ${CMAKE_CURRENT_SOURCE_DIR}/suite/usesfenv.t
)
