# GitHub CI configuration file for LuaVela.
# Copyright (C) 2020-2025 LuaVela Authors. See Copyright Notice in COPYRIGHT
# Copyright (C) 2015-2020 IPONWEB Ltd. See Copyright Notice in COPYRIGHT

name: Setup CI environment on macOS
description: Common part to tweak macOS CI runner environment
runs:
  using: composite
  steps:
    - name: Setup CI environment
      uses: ./.github/actions/setup
    - name: Set CMAKE_BUILD_PARALLEL_LEVEL
      run: |
        # Set CMAKE_BUILD_PARALLEL_LEVEL environment variable to
        # limit the number of parallel jobs for build/test step.
        NPROC=$(sysctl -n hw.logicalcpu 2>/dev/null)
        echo CMAKE_BUILD_PARALLEL_LEVEL=$(($NPROC + 1)) | tee -a $GITHUB_ENV
      shell: bash
