#!/usr/bin/env bash

cmake -H. -B${BUILD_DIR} \
    -DCMAKE_BUILD_TYPE=Debug \
    -DUJIT_HAS_JIT=OFF \
    -DUJIT_HAS_FFI=OFF \
    -DUJIT_LUA52COMPAT=OFF \
    -DUJIT_ENABLE_GDBJIT=OFF \
    -DUJIT_ENABLE_PROFILER=OFF \
    -DUJIT_ENABLE_IPROF=OFF \
    -DUJIT_ENABLE_COVERAGE=OFF \
    -DUJIT_ENABLE_CO_TIMEOUT=OFF \
    -DUJIT_ENABLE_MEMPROF=OFF \
    -DUJIT_ENABLE_THREAD_SAFETY=OFF
